### ISSUE TITLE
Adding Discord Token Issue

### ISSUE THREAD

**Issue by adamsky-01** [parotic0/NSTool#2]
I just getting errors as per below. It seems like the Twitters keys are ok just there is something wrong with the Discord token ...or code, as I'm pretty sure my Discord token is  fine too.

Successfully connected to twitter
? Enter discord auth token:   xxxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "D:\bot\nst\main.py", line 410, in getKEYSfromuser
    auth = resp1['First Discord Auth key']
KeyError: 'First Discord Auth key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bot\nst\main.py", line 642, in <module>
    getKEYSfromuser()
  File "D:\bot\nst\main.py", line 426, in getKEYSfromuser
    except tempapi.TwitterError:
AttributeError: 'Api' object has no attribute 'TwitterError'

D:\bot\nst>

**Comment by parotic0** [comment]
this definitely sounds like something i've broken, are you running the latest version and have all the dependencies been installed? just checking before i start work on fixing.

**Comment by parotic0** [comment]
i've updated the code, i think i've fixed the both the issues.
if anything else comes up let me know and ill try and fix it asap

**Comment by adamsky-01** [comment]
I'm afraid it's still not working as intended.
```
'clear' is not recognized as an internal or external command,
operable program or batch file.
              ______            __
   ____  ____/_  __/___  ____  / /____
  / __ \/ ___// / / __ \/ __ \/ / ___/
 / / / (__  )/ / / /_/ / /_/ / (__  )
/_/ /_/____//_/  \____/\____/_/____/


0 - sets of api keys loaded  |   0 - discord auth keys loaded | 🖓 - API connection
We cant seem to find your keys please enter them below:
? Enter consumer key:   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
? Enter consumer secret key:   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
? Enter access token key:   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
? Enter access token secret key:   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "D:\bot\nst\main.py", line 640, in <module>
    getKEYSfromuser()
  File "D:\bot\nst\main.py", line 401, in getKEYSfromuser
    tempapi = twitter.Api(consumer_key=consumer_key_array, consumer_secret=consumer_secret_array, access_token_key=access_token_array, access_token_secret=access_secret_array)
AttributeError: module 'twitter' has no attribute 'Api'

D:\bot\nst>
```

**Comment by parotic0** [comment]
ok thats weird, i can assume your running windows but are you using powershell or cmd?
but i havent ran into that issue while testing it on my own, i'll try and get a fix by tonight
