### ISSUE TITLE
Adding Twitter Api ,discord token and running file

### ISSUE THREAD

**Issue by Spikz** [parotic0/NSTool#4]
Hey I was just wondering where I can add the twitter api and discord token. Also do i just run the file with python? This program is used to open links fast on twitter because im trying to get into a discord where they drop invite links. Thanks for the help

**Comment by Spikz** [comment]
*****This program is used to open links fast on twitter because im trying to get into a discord where they drop invite links.****

**Comment by Spikz** [comment]
****Is This program is used to open links fast on twitter because im trying to get into a discord where they drop invite links.******

**Comment by parotic0** [comment]
yes this is exactly what you are looking for then. 
you should be given a prompt when you first run the script to input your tokens.
just run the script using "python *.py location" and you sould be good to go
lmk if you need anymore help

**Comment by Spikz** [comment]
Thank so much for responding. im not sure if I ran the file right but is it supposed to say this? What do I do next?
Traceback (most recent call last):
  File "C:\Users\Ivan\Desktop\NSTool-master\main.py", line 2, in <module>
    from PyInquirer import style_from_dict, Token, prompt, Separator
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInquirer\__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\key_binding\bindings\basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\__init__.py", line 8, in <module>
    from .from_dict import *
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)

**Comment by Spikz** [comment]
Hey I was just wondering if when I run the file it is supposed to say this 
C:\Users\Ivan\Desktop\NSTool-master>python main.py
Traceback (most recent call last):
  File "C:\Users\Ivan\Desktop\NSTool-master\main.py", line 2, in <module>
    from PyInquirer import style_from_dict, Token, prompt, Separator
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInquirer\__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\key_binding\bindings\basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\__init__.py", line 8, in <module>
    from .from_dict import *
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)

**Comment by parotic0** [comment]
have you installed the requirements.txt? that seems to be the issue

**Comment by Spikz** [comment]
I think I did im not completely sure in cmd I put "pip install (copy-pasted each from requirements.txt). I think its installed but I'm not sure. It still says this when i do "python main.py" in cmd

**Comment by Spikz** [comment]
I checked if I had the packages for requirments.txt by using "pip list" and they were all there with the same versions as in rewuirements.txt. I'm not sure what the problem is.

**Comment by Spikz** [comment]
Yea im not sure what i did wrong I tried off a different computer but it still didnt work

**Comment by Spikz** [comment]
I also did "pip install -r requirements.txt" but it still says
C:\Users\Ivan\Desktop\NSTool-master>python main.py
Traceback (most recent call last):
  File "C:\Users\Ivan\Desktop\NSTool-master\main.py", line 2, in <module>
    from PyInquirer import style_from_dict, Token, prompt, Separator
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInquirer\__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\key_binding\bindings\basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\__init__.py", line 8, in <module>
    from .from_dict import *
  File "C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\Ivan\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)

C:\Users\Ivan\Desktop\NSTool-master>

when i do "python main.py"
I hope I can get this issue solved im really not sure whats wrong. Do i need to imput my twitter api and discord somewhere before I run? idk

**Comment by Spikz** [comment]
Im sure sure what to do when you get the chance can you please tell me how to fix this :)
